apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: tstasse
  labels:
    app: sso
  namespace: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    username: tstasse
    firstName: Tim
    lastName: Stasse
    email: tstasse@redhat.com
    enabled: true
    emailVerified: true
    groups:
      - admin
    credentials:
      - temporary: false
        type: password
        value: tstasse
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: adam
  labels:
    app: sso
  namespace: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    username: adam
    firstName: Adam
    lastName: Adam
    email: adam@example.com
    enabled: true
    emailVerified: true
    groups:
      - team-a
    credentials:
      - temporary: false
        type: password
        value: adam
---              
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: amelie
  labels:
    app: sso
  namespace: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    username: amelie
    firstName: Amelie
    lastName: Amelie
    email: amelie@example.com
    enabled: true
    emailVerified: true
    groups:
      - team-a
    credentials:
      - temporary: false
        type: password
        value: amelie
---              
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: brad
  labels:
    app: sso
  namespace: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    username: brad
    firstName: Brad
    lastName: Brad
    email: brad@example.com
    enabled: true
    emailVerified: true
    groups:
      - team-b
    credentials:
      - temporary: false
        type: password
        value: brad
---              
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: brumilde
  labels:
    app: sso
  namespace: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    username: brumilde
    firstName: Brumilde
    lastName: Brumilde
    email: brumilde@example.com
    enabled: true
    emailVerified: true
    groups:
      - team-b
    credentials:
      - temporary: false
        type: password
        value: brumilde                
