apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  redhat-developer-hub

resources:
- ./namespace.yaml
- ./keycloak-client-secret-backstage.yaml
- ./patches-rbac.yaml
- ./patches.yaml
- ./postgresql-creds-secret.yaml
- ./link.yaml

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  # - name: backstage
  #   repo: https://janus-idp.github.io/helm-backstage
  #   releaseName: redhat-developer-hub
  #   namespace: redhat-developer-hub
  #   valuesFile: values.yaml
  - name: developer-hub
    releaseName: redhat-developer-hub
    namespace: redhat-developer-hub
    valuesFile: values.yaml  
