apiVersion: v1
kind: Secret
metadata:
  name: non-prod-install-config
  namespace: 'non-prod'
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: 'non-prod'
    baseDomain: ${PLATFORM_BASE_DOMAIN}
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.1.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: us-west-2
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFugfYjOzrj4PcOUY1n8cFuVRlahbmz/2pz9qFJ2HTH tstasse@DESKTOP-8JP9SKC
#data:
  # Base64 encoding of install-config yaml
  #install-config.yaml: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogJ25vbi1wcm9kJwpiYXNlRG9tYWluOiBjaHJpLnAxLm9wZW5zaGlmdGFwcHMuY29tCmNvbnRyb2xQbGFuZToKICBhcmNoaXRlY3R1cmU6IGFtZDY0CiAgaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiBtYXN0ZXIKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDQwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCmNvbXB1dGU6Ci0gaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBhcmNoaXRlY3R1cmU6IGFtZDY0CiAgbmFtZTogJ3dvcmtlcicKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDIwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCm5ldHdvcmtpbmc6CiAgbmV0d29ya1R5cGU6IE9WTkt1YmVybmV0ZXMKICBjbHVzdGVyTmV0d29yazoKICAtIGNpZHI6IDEwLjEyOC4wLjAvMTQKICAgIGhvc3RQcmVmaXg6IDIzCiAgbWFjaGluZU5ldHdvcms6CiAgLSBjaWRyOiAxMC4wLjAuMC8xNgogIHNlcnZpY2VOZXR3b3JrOgogIC0gMTcyLjMwLjAuMC8xNgpwbGF0Zm9ybToKICBhd3M6CiAgICByZWdpb246IHVzLXdlc3QtMgpwdWxsU2VjcmV0OiAiIiAjIHNraXAsIGhpdmUgd2lsbCBpbmplY3QgYmFzZWQgb24gaXQncyBzZWNyZXRzCnNzaEtleTogfC0KICAgIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQmdRQ1dWbk9FWUZhTjZ0cC9DWG41YUJnRDVZWmJid0pIaFVZYkFhaG9HejNJYlA4WVpad3lCdkp2Z3k5Q3VqS1RhSXBaSHdlWVJ3TUV0dlBhWDY1ZzhBUURkOHQ2R3FjK0pWSnVlNkhUcXJhd0gyd3ZxOFFkaGlwOUwwOWZLMldxdFA3VWJWRitmZ2l3bTlrZWJhamtBcXRsT3R0Y2RIaXBlUnk1VEdWRTJoYlYxenFjNlVqVG82bEt6eGZsbTJKZDVFTWM0VFpDbGVTRkFwQm9kK2pnRlpva2UvOFEvR0hXeVFzN1lhb0UzaC9KTkQ3ejZheWU1SG9BUFFCVDE4eS80QW13ajdoMmhJY0lzU0o4SkFIc09aME5CNGd6MXF3cGtHL2RZQVlWMWlBUk0vK3FuWjdFSkF0NERvZnFVQVMxLzBCZFhLKzFSTDh1STBkYjRyOFUzcFRlK29GR09SUUhSTmErZWhEb1gxUGRPVStvNTlPbWpFYUpwY3EwWVJCM05xT3dmWnpBVFVmT3FjWnN3SDB4QzZXS2kvVWtuQkZQZ0p2NkpmRDArZGVlL2tXVG1nRnJ6VDZJZTloUnFsMmJBK3FqU29QZld6UGsrR3YxV3VmNlVHZEMyRHBLUE8rdk9oVnpSdG9nL2N2d2pHU0p2NXAyWDZiaVJHaVl5OGEwYlgwPSByc3BhenpvbEByc3BhenpvbA==
