apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./cluster-deployment.yaml
  - ./install-config-secret.yaml
  - ./machine-pool.yaml
  - ./patches-rbac.yaml
  - ./aws-creds-secret.yaml
  - ./pull-secret.yaml
  - ./patches.yaml
  - ./private-key-secret.yaml

helmGlobals:
  chartHome: ../../../../.helm/charts

helmCharts:
  - name: cluster-registration
    releaseName: non-prod
    namespace: non-prod
    valuesInline: 
      clusterName: non-prod
      platformDomain: ${PLATFORM_BASE_DOMAIN}
      hubDomain: ${CLUSTER_BASE_DOMAIN}     
      clusterSet: default
      repoURL: https://github.com/tim-stasse/eaas-platform-iac.git
      labels:
        cloud: AWS
        vendor: OpenShift
        region: us-west-2

  - name: vault-cluster-registration
    releaseName: non-prod
    namespace: vault-admin
    valuesInline:
      cluster:
        apiUrl: https://api.non-prod.${PLATFORM_BASE_DOMAIN}:6443